name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: Reference to use for checking out
        default: ${{ github.sha }}
        type: string
      private:
        description: Use private dependencies & configuration
        default: false
        type: boolean

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  job:
    name: Build & Test ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # For Windows msvc, for Linux and macOS let's use the clang compiler.
        name: [macos-latest-clang, windows-latest-msvc, ubuntu-latest-clang]
        include:
          - name: windows-latest-msvc
            os: windows-latest
            cxx: cl.exe
            cc: cl.exe
            artifact: true
          - name: ubuntu-latest-clang
            os: ubuntu-latest
            cxx: clang++
            cc: clang
            artifact: true
          - name: macos-latest-clang
            os: macos-latest
            cxx: clang++
            cc: clang
            artifact: true

    env: 
      workingDir: build

    defaults:
      run:
        shell: bash

    steps:
    - name: Determine Reference
      id: version
      env:
        ref: ${{ inputs.ref }}
        sha: ${{ github.sha }}
      run: |
        if [ "$ref" == "" ] ; then
          ref=$sha
        fi
        echo "ref=$ref" >> $GITHUB_OUTPUT

    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.version.outputs.ref }}
        submodules: true
    
    - name: Install Dependencies
      run: |
        case "${RUNNER_OS}" in
          Linux)    sudo apt install ninja-build libboost-all-dev libzzip-dev libminizip-dev ;;
          macOS)    brew install ninja boost libzzip minizip ;;
          Windows)  choco install ninja boost-msvc-14.3 --no-progress
                    vcpkg install zziplib minizip --triplet x64-windows ;;
          *)        echo "Do not recognise ${RUNNER_OS}." && exit 1 ;;
        esac
      env:
        HOMEBREW_NO_ENV_HINTS: true
        VCPKG_DISABLE_METRICS: true

    - name: MSVC++ Environment
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Cache DX SDK
      id: dxcache
      if: runner.os == 'Windows'
      uses: actions/cache@v3
      with:
        path: '${{ github.workspace }}/DX_SDK'
        key: ${{ runner.os }}-DX_SDK
        restore-keys: |
          ${{ runner.os }}-DX_SDK

    - name: Download DXSetup
      if: runner.os == 'Windows' && steps.dxcache.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        curl -s -o DXSDK_Jun10.exe --location https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe
        .\DXSDK_Jun10.exe /U /O /F /S /P "${{ github.workspace }}\DX_SDK"
        [[ -f .\DXSDK_Jun10.exe ]] || dir /w 

    - name: Configure & Build
      run: |
        case "${RUNNER_OS}" in
          Linux)   conf="" ;;
          macOS)   conf="-DCMAKE_OSX_ARCHITECTURES='arm64;x86_64'" ;;
          Windows) conf="-DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_ASSIMP_VIEW=OFF"
                   export DCMAKE_TOOLCHAIN_FILE="${VCPKG_INSTALLATION_ROOT//\\//}/scripts/buildsystems/vcpkg.cmake"
                   conf="${conf} -DCMAKE_TOOLCHAIN_FILE=$DCMAKE_TOOLCHAIN_FILE" ;;
          *)       echo "Do not recognise ${RUNNER_OS}." && exit 1 ;;
        esac
        if [ "$private" == "true" ] ; then
          echo "Using private configuration."
          args="$args -DASSIMP_NO_EXPORT=ON"
        fi
        mkdir $workingDir && cd $workingDir
        echo "Configuring with: $conf"
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ${conf}
        echo "---"
        cmake --build . -- -j 24 -v
      env:
        DXSDK_DIR: '${{ github.workspace }}/DX_SDK'
        private: ${{ inputs.private }}

    - name: Test
      run: |
        cd $workingDir/bin
        ./unit

    - uses: actions/upload-artifact@v3
      if: matrix.artifact == true
      with:
        name: 'assimp-${{ matrix.name }}'
        path: ${{ env.workingDir }}/bin/*
