name: CIFuzz
on: [pull_request]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        case "${RUNNER_OS}" in
          Linux)    sudo apt install libboost-all-dev;;
          macOS)    brew install boost ;;
          Windows)  choco install boost-msvc-14.3;;
          *)        echo "Do not recognise ${RUNNER_OS}." && exit 1 ;;
        esac
      env:
        HOMEBREW_NO_ENV_HINTS: true

    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'assimp'
        dry-run: false
        language: c++
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'assimp'
        fuzz-seconds: 300
        dry-run: false
        language: c++
    - name: Upload Crash
      uses: actions/upload-artifact@v3
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
