name: C/C++ Sanitizer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  sanitize:
    name: Sanitizers
    id: adress-sanitizer
    runs-on: ubuntu-latest
    env: 
      workingDir: build
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt install ninja-build libboost-all-dev;;

    - name: Configure & Build
      run: |
        mkdir $workingDir && cd $workingDir
        # Note: each instance of args is empty if not building for that platform
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DASSIMP_ASAN=ON
        cmake --build . -- -j 24 -v

    - name: Address Sanitizer
      run: cd $workingDir/bin && ./unit
      shell: bash

    - name: Clean
      run: rm $workingDir -Rf
      shell: bash

    - name: Configure & Build
      run: |
        mkdir $workingDir && cd $workingDir
        # Note: each instance of args is empty if not building for that platform
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DASSIMP_UBSAN=ON
        cmake --build . -- -j 24 -v

    - name: Unidentified Behaviour Sanitizer
      run: cd $workingDir/bin && ./unit
      shell: bash
